# This file was generated by GoReleaser. DO NOT EDIT.
class Ascii2svg < Formula
  desc "ascii2svg"
  homepage "https://manfred.life/"
  version "1.0.0"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/moul/ascii2svg/releases/download/v1.0.0/ascii2svg_1.0.0_Darwin_x86_64.tar.gz"
    sha256 "0b5475d6fa81ce65b4840db3d4fca0013ef9637f68cee73edb6bba2cce0acdb8"
  elsif OS.linux?
    url "https://github.com/moul/ascii2svg/releases/download/v1.0.0/ascii2svg_1.0.0_Linux_x86_64.tar.gz"
    sha256 "2db97a03a244febdca2fdb0d86d6af097eff597e896b9da1ff666aff1ac19962"
  end

  def install
    bin.install "ascii2svg"
  end
end
