# This file was generated by GoReleaser. DO NOT EDIT.
class Cryptoguess < Formula
  desc "cryptoguess"
  homepage "https://manfred.life/"
  version "1.0.0"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/moul/cryptoguess/releases/download/v1.0.0/cryptoguess_1.0.0_Darwin_x86_64.tar.gz"
    sha256 "8a5f7e857a3420d234b60b0fd1f47140c28c3a8503e6d7474614e29aed1d949c"
  elsif OS.linux?
    url "https://github.com/moul/cryptoguess/releases/download/v1.0.0/cryptoguess_1.0.0_Linux_x86_64.tar.gz"
    sha256 "5e9fce76b7cb42e3d544d7ab6acbfe5cf45bc1580d4244b97bbb44b614631074"
  end

  def install
    bin.install "cryptoguess"
  end
end
