# This file was generated by GoReleaser. DO NOT EDIT.
class Cryptoguess < Formula
  desc "cryptoguess"
  homepage "https://manfred.life/"
  version "1.1.0"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/moul/cryptoguess/releases/download/v1.1.0/cryptoguess_1.1.0_Darwin_x86_64.tar.gz"
    sha256 "6c67323402a38d67b751469956b33421d9323348293482b42b33d7ed915cd10f"
  elsif OS.linux?
    url "https://github.com/moul/cryptoguess/releases/download/v1.1.0/cryptoguess_1.1.0_Linux_x86_64.tar.gz"
    sha256 "f4cb5176afa728548800441a0ff9c703b4c9290a01b3aca3708796e51baff3d1"
  end

  def install
    bin.install "cryptoguess"
  end
end
