# This file was generated by GoReleaser. DO NOT EDIT.
class Cryptoguesser < Formula
  desc "cryptoguesser"
  homepage "https://manfred.life/"
  version "1.0.0"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/moul/cryptoguesser/releases/download/v1.0.0/cryptoguesser_1.0.0_Darwin_x86_64.tar.gz"
    sha256 "d62215d389a6410a595d71019c848ea4a9f8ce8a800585702b146d0f37c08d96"
  elsif OS.linux?
    url "https://github.com/moul/cryptoguesser/releases/download/v1.0.0/cryptoguesser_1.0.0_Linux_x86_64.tar.gz"
    sha256 "7d2b7f0c0484dd3a7f6ac86545b621de2e9f4fc99e4d39251a6aa54e417ca158"
  end

  def install
    bin.install "cryptoguesser"
  end
end
