# This file was generated by GoReleaser. DO NOT EDIT.
class Dl < Formula
  desc "dl"
  homepage "https://manfred.life/"
  version "1.3.0"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/moul/dl/releases/download/v1.3.0/dl_1.3.0_Darwin_x86_64.tar.gz"
    sha256 "6e9672f44b6d34463c42b27230d1b211baf02710571259bd43b307524daf4600"
  elsif OS.linux?
    url "https://github.com/moul/dl/releases/download/v1.3.0/dl_1.3.0_Linux_x86_64.tar.gz"
    sha256 "31be21c5f5e947479d55b11a30d7185f441414fa7fff322274ac0c7965f6a2be"
  end

  def install
    bin.install "dl"
  end
end
