# This file was generated by GoReleaser. DO NOT EDIT.
class FsBundler < Formula
  desc "fs-bundler"
  homepage "https://manfred.life/"
  url "https://github.com/moul/fs-bundler/releases/download/v1.2.0/fs-bundler_1.2.0_darwin_amd64.tar.gz"
  version "1.2.0"
  sha256 "ed7c2900f1621fa4f9ca9723f3c134da0eec1f64306f13966f0e961bb3b46d5a"

  def install
    bin.install "fs-bundler"
  end
end
