# This file was generated by GoReleaser. DO NOT EDIT.
class GolangRepoTemplate < Formula
  desc "golang-repo-template"
  homepage "https://manfred.life/"
  url "https://github.com/moul/golang-repo-template/releases/download/v1.0.0/golang-repo-template_1.0.0_darwin_amd64.tar.gz"
  version "1.0.0"
  sha256 "63a135bcb63f6fa8e60d3f7858cbc18f926648658a47539ff79455586c9568ac"

  def install
    bin.install "golang-repo-template"
  end
end
