# This file was generated by GoReleaser. DO NOT EDIT.
class Graphman < Formula
  desc "graph manipulation library and tool"
  homepage "https://manfred.life/"
  version "1.4.0"

  if OS.mac?
    url "https://github.com/moul/graphman/releases/download/v1.4.0/graphman_1.4.0_darwin_amd64.tar.gz"
    sha256 "8c422afdc8faf2f88d793b5a810cb9f6eba9d619dd7b3520b3a6cfcd2861b23f"
  elsif OS.linux?
    url "https://github.com/moul/graphman/releases/download/v1.4.0/graphman_1.4.0_linux_amd64.tar.gz"
    sha256 "4956d0275a1905a0c068099c901823f49cf78e51926c68215cd45483a1e0e0a5"
  end

  def install
    bin.install "pertify"
  end
end
