# This file was generated by GoReleaser. DO NOT EDIT.
class Moulsay < Formula
  desc "moulsay"
  homepage "https://manfred.life/"
  version "1.0.0"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/moul/moulsay/releases/download/v1.0.0/moulsay_1.0.0_Darwin_x86_64.tar.gz"
    sha256 "ce4249b901b91b60de802e03ef146f5c2a1b474c5460999a3528dccf4db94d39"
  elsif OS.linux?
    url "https://github.com/moul/moulsay/releases/download/v1.0.0/moulsay_1.0.0_Linux_x86_64.tar.gz"
    sha256 "ec6ed96d8e8ffaf015eb5e2703b216c70a3e234053ec80598b3e365f7702b509"
  end

  def install
    bin.install "moulsay"
  end
end
