# This file was generated by GoReleaser. DO NOT EDIT.
class Moulsay < Formula
  desc "moulsay"
  homepage "https://manfred.life/"
  version "1.1.0"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/moul/moulsay/releases/download/v1.1.0/moulsay_1.1.0_Darwin_x86_64.tar.gz"
    sha256 "6bbefbda8ee253f75735cd56586bb9dcd78c981978dee3cd39c9160141736164"
  elsif OS.linux?
    url "https://github.com/moul/moulsay/releases/download/v1.1.0/moulsay_1.1.0_Linux_x86_64.tar.gz"
    sha256 "7505447e215991c056a7f9eb42714a8bd8869a8a83ecbd49f166347ede7969a5"
  end

  def install
    bin.install "moulsay"
  end
end
