# This file was generated by GoReleaser. DO NOT EDIT.
class Moulsay < Formula
  desc "moulsay"
  homepage "https://manfred.life/"
  version "1.2.0"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/moul/moulsay/releases/download/v1.2.0/moulsay_1.2.0_Darwin_x86_64.tar.gz"
    sha256 "89c039b862fcd07942e867fd0382f61a40bd4eb5acd70cffa00b619d20d6b55e"
  elsif OS.linux?
    url "https://github.com/moul/moulsay/releases/download/v1.2.0/moulsay_1.2.0_Linux_x86_64.tar.gz"
    sha256 "ce348ce0e70dd8de8ebd29d9460ad6d070bdbbcae78b96e773eeab2c13535410"
  end

  def install
    bin.install "moulsay"
  end
end
