# This file was generated by GoReleaser. DO NOT EDIT.
class MusicPaint < Formula
  desc "music-paint"
  homepage "https://manfred.life/"
  url "https://github.com/moul/music-paint/releases/download/v1.0.0/music-paint_1.0.0_Darwin_x86_64.tar.gz"
  version "1.0.0"
  sha256 "d0a1805263102e7fd6acd01554fab6fa870cefe8a9723dbdd642a15c7be2b4d8"

  def install
    bin.install "music-paint"
  end
end
