# This file was generated by GoReleaser. DO NOT EDIT.
class NumberToWords < Formula
  desc "number-to-words"
  homepage "https://manfred.life/"
  version "0.4.0"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/moul/number-to-words/releases/download/v0.4.0/number-to-words_0.4.0_Darwin_x86_64.tar.gz"
    sha256 "bd80cc0842f4c7189445a2b90150d6f67d1c42139fe2bcbe699786ba9908d98f"
  elsif OS.linux?
    url "https://github.com/moul/number-to-words/releases/download/v0.4.0/number-to-words_0.4.0_Linux_x86_64.tar.gz"
    sha256 "086123374429b245bffeeb1c3855cc109952b5e701785f7176dd603cd88b00de"
  end

  def install
    bin.install "number-to-words"
  end
end
