# This file was generated by GoReleaser. DO NOT EDIT.
class Pipotron < Formula
  desc "Generic (funny) text generator"
  homepage "https://manfred.life/geneator"
  url "https://github.com/moul/pipotron/releases/download/v1.1.0/pipotron_1.1.0_darwin_amd64.tar.gz"
  version "1.1.0"
  sha256 "2393ea6ee810e49708cf4b522cbeaf71764b14983e18cda143bc3886197c997b"

  def install
    bin.install "pipotron"
  end
end
