# This file was generated by GoReleaser. DO NOT EDIT.
class Quicssh < Formula
  desc "quicssh"
  homepage "https://manfred.life/"
  url "https://github.com/moul/quicssh/releases/download/v1.0.0/quicssh_1.0.0_darwin_amd64.tar.gz"
  version "1.0.0"
  sha256 "3bcaaee314c7d7deb4337483183fb46fb602997cfb15a75cdcd75dac0a4d7fec"

  def install
    bin.install "quicssh"
  end
end
