# This file was generated by GoReleaser. DO NOT EDIT.
class Retry < Formula
  desc "retry: repeat shell commands"
  homepage "https://manfred.life/"
  version "0.6.0"

  if OS.mac?
    url "https://github.com/moul/retry/releases/download/v0.6.0/retry_0.6.0_Darwin_x86_64.tar.gz"
    sha256 "e3c0bda0ae2007207121e981316dc1b34f816c12281a841b2e04ca4b85268e04"
  elsif OS.linux?
    url "https://github.com/moul/retry/releases/download/v0.6.0/retry_0.6.0_Linux_x86_64.tar.gz"
    sha256 "588ae58ab8a8fe2454f17d1d04b8f1b02ce2e04a9846ccca6ec51a02d922d859"
  end

  def install
    bin.install "retry"
  end
end
