# This file was generated by GoReleaser. DO NOT EDIT.
class Sshportal < Formula
  desc "Simple, fun and transparent SSH (and telnet) bastion"
  homepage "https://manfred.life/sshportal"
  version "1.10.0"

  if OS.mac?
    url "https://github.com/moul/sshportal/releases/download/v1.10.0/sshportal_1.10.0_darwin_amd64.tar.gz"
    sha256 "5bf2b351904de4d20eee5a3502f518103d28859b703acb01083f3b1ecc912a06"
  elsif OS.linux?
    url "https://github.com/moul/sshportal/releases/download/v1.10.0/sshportal_1.10.0_linux_amd64.tar.gz"
    sha256 "aa068b1be25b59a73c4474d39206583cf9450e6daf37cbc4603ec84ab2bd2367"
  end

  def install
    bin.install "sshportal"
  end
end
