# This file was generated by GoReleaser. DO NOT EDIT.
class TotpKeychain < Formula
  desc "TOTP cli backed by the OS X keychain"
  homepage "https://manfred.life/cryptography"
  url "https://github.com/moul/totp-keychain/releases/download/v1.0.1/totp-keychain_1.0.1_darwin_amd64.tar.gz"
  version "1.0.1"
  sha256 "6a4a73ba2660b7de16daa4dee48cfc7fcc8e8715303f50d7334d5c5bb635f6a3"

  def install
    bin.install "totp-keychain"
  end
end
